// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvx9Y1AH-lKrKhD4fH2oz5CcypUt2cq7A',
    appId: '1:942300350864:web:cad0619b6d0642af460b15',
    messagingSenderId: '942300350864',
    projectId: 'feild-selles-app',
    authDomain: 'feild-selles-app.firebaseapp.com',
    storageBucket: 'feild-selles-app.firebasestorage.app',
    measurementId: 'G-J4X7JC7WE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmpSL5ZRXHgph_TlGBeAefqkg56FdxOqY',
    appId: '1:942300350864:android:5b475c6a54d6ba12460b15',
    messagingSenderId: '942300350864',
    projectId: 'feild-selles-app',
    storageBucket: 'feild-selles-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2je_Q2b4szXZV3_wqFJK1eTi9YmglZgg',
    appId: '1:942300350864:ios:5e2ef6d88f1755cf460b15',
    messagingSenderId: '942300350864',
    projectId: 'feild-selles-app',
    storageBucket: 'feild-selles-app.firebasestorage.app',
    iosBundleId: 'com.example.fieldSalesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2je_Q2b4szXZV3_wqFJK1eTi9YmglZgg',
    appId: '1:942300350864:ios:5e2ef6d88f1755cf460b15',
    messagingSenderId: '942300350864',
    projectId: 'feild-selles-app',
    storageBucket: 'feild-selles-app.firebasestorage.app',
    iosBundleId: 'com.example.fieldSalesApp',
  );
}
